# Generated by Django 3.0.1 on 2021-01-17 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='chats',
            field=models.ManyToManyField(blank=True, to='main.Message'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user2',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='person2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='user1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='person1', to=settings.AUTH_USER_MODEL),
        ),
    ]
